updated github workflow

diff --git a/.github/workflows/hellow-world.yml b/.github/workflows/hellow-world.yml
--- a/.github/workflows/hellow-world.yml
+++ b/.github/workflows/hellow-world.yml
@@ -38,7 +38,7 @@ jobs:
           # Commands to build and deploy your application
           # If deployment fails, exit with a non-zero status code
           # For example:
-          npm run build || exit 1
+          # npm run build || exit 1
 
       - name: Notify on Failure
         env:
@@ -83,31 +83,31 @@ jobs:
   #           -d "text=$successMessage" \
   #           https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage)
 
-  notify:
-    needs: deploy
-    runs-on: ubuntu-latest
-    if: ${{ always() }} # Ensure this job runs regardless of the outcome of previous jobs
-    steps:
-      - name: Notify on Failure
-        env:
-          TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
-          CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
-        if: ${{ failure() }}
-        run: |
-          successMessage="Deployment failed! Sending notification..."
-          response=$(curl -s -X POST \
-            -d "chat_id=$CHAT_ID" \
-            -d "text=$successMessage" \
-            https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage)
+  # notify:
+  #   needs: deploy
+  #   runs-on: ubuntu-latest
+  #   if: ${{ always() }} # Ensure this job runs regardless of the outcome of previous jobs
+  #   steps:
+  #     - name: Notify on Failure
+  #       env:
+  #         TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
+  #         CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
+  #       if: ${{ failure() }}
+  #       run: |
+  #         successMessage="Deployment failed! Sending notification..."
+  #         response=$(curl -s -X POST \
+  #           -d "chat_id=$CHAT_ID" \
+  #           -d "text=$successMessage" \
+  #           https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage)
 
-      - name: Notify on Success
-        env:
-          TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
-          CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
-        if: ${{ success() }}
-        run: |
-          successMessage="Deployment successful! Sending notification..."
-          response=$(curl -s -X POST \
-            -d "chat_id=$CHAT_ID" \
-            -d "text=$successMessage" \
-            https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage)
+  #     - name: Notify on Success
+  #       env:
+  #         TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
+  #         CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
+  #       if: ${{ success() }}
+  #       run: |
+  #         successMessage="Deployment successful! Sending notification..."
+  #         response=$(curl -s -X POST \
+  #           -d "chat_id=$CHAT_ID" \
+  #           -d "text=$successMessage" \
+  #           https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage)
